const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function context(){
 const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'0',disabled:false,classList:{add(){},remove(){},toggle(){}},innerText:'',textContent:''});return nodes.get(id);};
 const ctx=vm.createContext({console,Math,Date,document:{getElementById:node},localStorage:{getItem(){return null;}},showNotification(){},updatePitcherSelect(){},updateGameScreen(){},requirePitcherSelectionForCurrentHalfInning(){},keepLiveGameSectionsEnabled(){},persistLiveGameAutosave(){},updatePublicAccessUI(){},showGameOver(){}});
 for(const f of ['core.state.js','core.schedule.js','core.stats.js','app.game.state.js','app.game.runners.js','app.game.rules.js','app.game.play.js','app.game.save.js','app.game.views.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx,{filename:f});
 vm.runInContext(`finalizeCompletedGame=()=>{game._gameCompletePendingSave=true;return true;};leagueSettings={weeks:6,innings:1,outs:2,maxPlayers:4,seriesLength:3};season=createEmptySeasonState();season.rules={...leagueSettings};game={rules:{...leagueSettings},team1:{name:'A',players:['A1','A2']},team2:{name:'B',players:['B1','B2']},team1Score:0,team2Score:0,inning:1,halfInning:'top',outs:0,halfInningRuns:0,bases:{first:null,second:null,third:null},gameStats:{},currentInningPitchers:{},batterIndexByTeam:{A:0,B:0},lineScore:{},overtime:normalizeOvertimeState(),_gameInstanceId:'manual-test'};game.batting=game.team1;game.fielding=game.team2;league={teams:[game.team1,game.team2]};for(const t of league.teams)for(const name of t.players)game.gameStats[getPlayerKey(t.name,name)]=createEmptyStats(t.name,name);`,ctx);
 ctx.eval=s=>vm.runInContext(s,ctx);ctx.play=(result,pitcher=0)=>{node('pitcherSelect').value=String(pitcher);ctx.result=result;ctx.eval(`{const name=game.batting.players[getCurrentBatterIndex()];pendingBattingResult={result,batter:name,batterKey:getGameStatsKey(game.batting,name)};recordPitchingResult('clean');}`);};ctx.data=s=>JSON.parse(JSON.stringify(ctx.eval(s)));return ctx;
}
for(const n of [1,3,5,7,9])test(`best of ${n}: majority clinches, unused fixtures excluded, correction reopens`,()=>{
 const c=context();c.n=n;const e=c.eval(`createSeriesEntry('A','B',1,n)`);c.e=e;
 for(let i=0;i<(n+1)/2;i++)e.gamesInSeries[i].result={type:'win',winner:'A',loser:'B',playedAt:i+1};
 c.eval('reconcileSeriesClinch(e)');assert.equal(e.result.winner,'A');assert.equal(e.gamesInSeries.filter(g=>g.skipped).length,(n-1)/2);assert.equal(e.gamesInSeries.filter(g=>g.result).length,(n+1)/2);
 e.gamesInSeries[0].result=null;c.eval('reconcileSeriesClinch(e)');assert.equal(e.result,null);assert.equal(e.gamesInSeries.filter(g=>g.skipped).length,0);
});
for(const winners of [['A','B','A'],['A','B','A','B','A']])test(`${winners.length}-game split series stays in progress until final majority`,()=>{const c=context();c.n=winners.length;c.eval("e=createSeriesEntry('A','B',1,n)");for(let i=0;i<winners.length;i++){c.w=winners[i];c.i=i;c.eval("e.gamesInSeries[i].result={type:'win',winner:w};reconcileSeriesClinch(e)");assert.equal(c.eval('!!e.result'),i===winners.length-1);}});
test('legacy 2-0 schedule stays legacy until its explicit skipped final game',()=>{const c=context();c.eval("e=createSeriesEntry('A','B',1,3);delete e.bestOf;e.gamesInSeries[0].result={type:'win',winner:'A'};e.gamesInSeries[1].result={type:'win',winner:'A'}");assert.equal(c.eval('computeSeriesResult(e)'),null);c.eval("e.gamesInSeries[2].skipped={reason:'series_clinched'}");assert.equal(c.eval('computeSeriesResult(e).winner'),'A');});
test('2–8 teams and best of 1/3/5 have one opponent/week and fair partial-cycle byes',()=>{const c=context();for(let n=2;n<=8;n++)for(const bestOf of [1,3,5])for(const weeks of [1,3,6,11,52]){c.n=n;c.bestOf=bestOf;c.weeks=weeks;const s=c.eval('game=null;activeAccess={};leagueSettings={weeks,innings:3,outs:2,seriesLength:bestOf};season.rules={...leagueSettings};generateWeeklySchedule(Array.from({length:n},(_,i)=>({name:`T${i}`})),weeks)');const byes=Array(n).fill(0);for(const day of s.days){const teams=day.games.flatMap(e=>[e.away,e.home]);assert.equal(teams.length,new Set(teams).size);for(const e of day.games)assert.equal(e.gamesInSeries.length,bestOf);if(n%2)byes[Number(day.byeTeam.slice(1))]++;}if(n%2)assert.ok(Math.max(...byes)-Math.min(...byes)<=1);c.s=s;assert.equal(c.eval('isScheduleCurrentFormat(s,s.teamNames)'),true);}});
test('ERA uses regulation scope; credited outs use their saved denominator; WHIP has no length multiplier',()=>{const c=context();assert.equal(c.eval('eraValue({earnedRunsAllowed:2,pitchOuts:12,outsPerInning:2,regulationInnings:3})'),1);assert.equal(c.eval('formatStatRate(eraValue({earnedRunsAllowed:2,pitchOuts:12,outsPerInning:2},{rules:{innings:5}}))'),'1.67');assert.equal(c.eval('getPitchingInningsValue({pitchOuts:3,outsPerInning:2})'),1.5);assert.equal(c.eval('getPitchingInningsValue({pitchOuts:3,outsPerInning:3})'),1);assert.equal(c.eval('whipValue({pitchOuts:3,outsPerInning:2,pitchingCountsKnown:true,pitchWalksAllowed:1,pitchHitsAllowed:2,hitByPitch:9,fieldingErrors:7})'),2);assert.equal(c.eval('eraValue({pitchOuts:0,earnedRunsAllowed:0})'),null);assert.equal(c.eval('whipValue({pitchOuts:3,pitchHitsAllowed:0})'),null);});
test('mixed out rules sum numeric workload instead of applying current outs retroactively',()=>{const c=context();c.eval("s=createEmptyStats('A','A1');aggregatePitchingLine(s,{pitchOuts:3,outsPerInning:2,pitchingCountsKnown:true});s.pitchOuts+=3;aggregatePitchingLine(s,{pitchOuts:3,outsPerInning:3,pitchingCountsKnown:true});s.pitchOuts+=3;s.earnedRunsAllowed=2");assert.equal(c.eval('getPitchingInningsValue(s)'),2.5);assert.ok(Math.abs(c.eval('eraValue(s,{rules:{innings:3}})')-2.4)<1e-12);});
test('golden complete 3–2 game: independently hand-scored counts, team totals, rebuild and export agree',()=>{
 const c=context();for(const outcome of ['single','double','HR','walk','HBP','out','K','single','HR','K','out'])c.play(outcome);
 assert.deepEqual(c.data('[game.team1Score,game.team2Score,game._gameCompletePendingSave]'),[3,2,true]);
 const lines=c.data('game.gameStats');for(const [player,expected] of Object.entries({A1:{atBats:3,hits:2,singles:1,homeRuns:1,hitByPitch:1,strikeouts:1,rbis:3,runsScored:2,pitchOuts:2,pitchStrikeouts:1,runsAllowed:2,earnedRunsAllowed:2,pitchHitsAllowed:2,pitchWalksAllowed:0},A2:{atBats:2,hits:1,doubles:1,walks:1,outs:1,runsScored:1},B1:{atBats:2,hits:1,singles:1,strikeouts:1,runsScored:1,pitchOuts:2,pitchStrikeouts:1,runsAllowed:3,earnedRunsAllowed:3,pitchHitsAllowed:3,pitchWalksAllowed:1},B2:{atBats:2,hits:1,homeRuns:1,outs:1,rbis:2,runsScored:1}})){const line=lines[(player.startsWith('A')?'A':'B')+'|'+player];for(const field of c.eval('STATS_BACKUP_NUMERIC_FIELDS'))assert.equal(line[field],expected[field]||0,player+' '+field);}
 c.eval('server={season_json:season,schedule_json:{days:[],teamNames:[]}};finished=buildFinalLeagueSnapshot(server);season=finished.season;schedule=finished.schedule');
 assert.equal(c.eval('season.games.length'),1);assert.equal(c.eval("getSeasonTeamTotals(league.teams[0]).hits"),3);assert.equal(c.eval("getSeasonTeamTotals(league.teams[1]).pitchHitsAllowed"),3);assert.equal(c.eval("whipValue(season.playerStats['B|B1'])"),4);assert.equal(c.eval("getSeasonTeamTotals(league.teams[0]).inningsPitched"),1);
 assert.equal(c.eval("battingRates(season.playerStats['A|A1']).obp"),0.75);assert.equal(c.eval("battingRates(season.playerStats['A|A1']).slg"),5/3);
 const original=c.data('season.playerStats'),rebuilt=c.data('rebuildSeasonStatBucketsFromGameLogs(season).playerStats');for(const key of Object.keys(original))for(const field of c.eval('STATS_BACKUP_NUMERIC_FIELDS'))assert.equal(rebuilt[key][field],original[key][field],key+' '+field);
 const backup=c.data('createStatsBackupPayload()');assert.deepEqual(backup.season.games[0].playerStats,Object.values(lines));
});
test('inherited runner charged to original pitcher, later outs/hits to relief pitcher',()=>{const c=context();c.play('single',0);c.play('HR',1);c.play('K',1);c.play('out',1);assert.equal(c.eval("game.gameStats['B|B1'].runsAllowed"),1);assert.equal(c.eval("game.gameStats['B|B1'].pitchOuts"),0);assert.equal(c.eval("game.gameStats['B|B2'].runsAllowed"),1);assert.equal(c.eval("game.gameStats['B|B2'].pitchOuts"),2);assert.equal(c.eval("game.gameStats['B|B2'].pitchHitsAllowed"),1);});
test('ROE correction removes hit and RBI, retains AB/run and original pitching responsibility; undo restores',()=>{const c=context();c.play('double');c.play('double');const before=c.data('game.gameStats');c.eval('applyConfirmError()');assert.equal(c.eval("game.gameStats['A|A2'].hits"),0);assert.equal(c.eval("game.gameStats['A|A2'].atBats"),1);assert.equal(c.eval("game.gameStats['A|A2'].rbis"),0);assert.equal(c.eval("game.gameStats['B|B1'].pitchHitsAllowed"),1);assert.equal(c.eval("game.gameStats['B|B1'].earnedRunsAllowed"),0);assert.equal(c.eval('game.team1Score'),1);c.eval('restoreGameState(gameHistory.pop())');assert.deepEqual(c.data('game.gameStats'),before);});
test('overtime preset out creates no pitching workload; automatic runner scores team run and RBI only',()=>{const c=context();c.eval("game.inning=2;game.batting=game.team1;game.fielding=game.team2;startOvertimeHalfInning()");assert.equal(c.eval('game.outs'),1);assert.equal(c.eval("game.gameStats['B|B1'].pitchOuts"),0);c.play('double');assert.equal(c.eval('game.team1Score'),1);assert.equal(c.eval("game.gameStats['A|A1'].rbis"),1);assert.equal(c.eval("game.gameStats['A|A2'].runsScored"),0);assert.equal(c.eval("game.gameStats['B|B1'].earnedRunsAllowed"),0);c.play('K');assert.equal(c.eval("game.gameStats['B|B1'].pitchOuts"),1);});
test('duplicate logs cannot double totals; postseason remains separate',()=>{const c=context();c.eval("line=createEmptyStats('A','A1');line.hits=1;line.singles=1;line.atBats=1;season.games=[{id:'x',playerStats:[line]},{id:'x',playerStats:[line]},{id:'p',postseasonRef:{},playerStats:[line]}]");assert.equal(c.eval("rebuildSeasonStatBucketsFromGameLogs(season).playerStats['A|A1'].hits"),1);});
