// Browser UI checks with synthetic in-memory data. No live backend/security claims.
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let server,browser;const errors=[],results=[];let network=0;
function pass(s){results.push(s);console.log('PASS '+s);}
async function screenshot(page,name){await page.screenshot({path:'tests/'+name+'.png',fullPage:true});console.log('SCREENSHOT '+name+' '+(await page.screenshot({type:'jpeg',quality:50,fullPage:true})).toString('base64'));}
(async()=>{
 server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!/\.(html|js|css)$/.test(f)){res.writeHead(404);return res.end();}try{res.setHeader('content-type',f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'text/javascript');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(4173,'127.0.0.1',r));browser=await chromium.launch();
 for(const width of [1280,390]){
  const context=await browser.newContext({viewport:{width,height:900}});await context.route('https://*.supabase.co/**',async route=>{network++;const body=JSON.parse(route.request().postData()||'{}');await route.fulfill({contentType:'application/json',body:JSON.stringify({leagues:[],more:false})});});
  const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',msg=>{if(/Content Security Policy|violates.*directive/.test(msg.text()))errors.push(msg.text());});
  await p.goto('http://127.0.0.1:4173/app.html');await p.waitForFunction(()=>!directoryBusy);
  await p.locator('#directoryScreen button[data-wbl-click="f610aeac471a"]').click();await p.locator('#createName').fill('Community Wiffle League');await p.locator('#createCode').fill('Synthetic_UI8!');await p.locator('#createNext').click();
  await p.locator('#createMaxPlayers').fill('6');await p.locator('#createSeriesLength').selectOption('5');assert.ok((await p.locator('#createSummary').textContent()).includes('Best of 5'));assert.equal(await p.locator('#createSettingsScreen input').count(),4);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await screenshot(p,'series-settings-'+width);pass(width+'px two-step settings, odd choices, capacity and summary fit viewport');
  await p.evaluate(()=>{stopRealtime();creationDraft=null;clearCreationDraft();activeAccess={token:'synthetic'};LEAGUE_CODE='synthetic-ui';leagueName='Community Wiffle League';leagueSettings={weeks:6,innings:5,outs:3,maxPlayers:6,seriesLength:5};season=createEmptySeasonState();season.rules={...leagueSettings};league={teams:[{name:'Blue Jays',players:['Maya','Kai']},{name:'Red Foxes',players:['Jules']}]};schedule=generateWeeklySchedule(league.teams,6);game=null;showMainMenu();renderLeagueHeader();});
  const menu=p.locator('#leagueMenuButton');await menu.focus();await p.keyboard.press('ArrowDown');assert.equal(await menu.getAttribute('aria-expanded'),'true');assert.equal(await p.locator('#leagueMenuItems button').first().evaluate(e=>document.activeElement===e),true);await p.keyboard.press('End');assert.equal(await p.locator('#leagueMenuItems button').last().evaluate(e=>document.activeElement===e),true);await p.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert.equal(await menu.evaluate(e=>document.activeElement===e),true);pass(width+'px League menu supports arrow keys, End, Escape and focus return');
  await menu.click();await screenshot(p,'series-dashboard-menu-'+width);await p.locator('#activeLeagueTitle').click();assert.equal(await menu.getAttribute('aria-expanded'),'false');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));pass(width+'px dashboard and menu fit viewport; outside click closes');
  await menu.click();await p.locator('#leagueMenuItems button[data-wbl-click="a53ca03881a7"]').click();assert.equal(await p.locator('#settingsMaxPlayers').inputValue(),'6');assert.equal(await p.locator('#settingsSeriesLength').inputValue(),'5');await p.evaluate(()=>showMainMenu());assert.equal(await menu.getAttribute('aria-expanded'),'false');pass(width+'px menu opens settings populated from selected league');
  await p.evaluate(()=>{season.games=[{id:'g',rules:{innings:5,outs:3},team1Name:'Blue Jays',team2Name:'Red Foxes',team1Score:2,team2Score:0,lineups:{'Blue Jays':['Maya']},playerStats:[{...createEmptyStats('Blue Jays','Maya'),pitchOuts:3,outsPerInning:3,earnedRunsAllowed:1,runsAllowed:1,pitchHitsAllowed:2,pitchWalksAllowed:1}]}];const host=document.querySelector('#dashboardSummary');host.replaceChildren(createPastGamePitchingTable(season.games[0],'Blue Jays'));});
  assert.ok((await p.locator('#dashboardSummary').textContent()).includes('ERA (est., per 5 innings)'));const cells=await p.locator('#dashboardSummary tbody tr').first().locator('td').allTextContents();assert.equal(cells[1],'1.000');assert.equal(cells[6],'5.00');assert.equal(cells[7],'3.00');assert.equal(await p.locator('#dashboardSummary thead th').count(),cells.length);pass(width+'px saved-game ERA, decimal workload and WHIP columns match independent expected values');
  await context.close();
 }
 assert.deepEqual(errors,[]);pass('No uncaught application exceptions or CSP violations');
 fs.writeFileSync('tests/SERIES_UI_RESULTS.md','# Isolated browser UI results\n\nSynthetic in-memory UI fixture; backend requests intercepted. These checks do not validate real RPC authorization, concurrency, persistence or full E2E.\n\n'+results.map(s=>'- PASS: '+s).join('\n')+'\n');console.log(results.length+' UI checks passed; '+network+' requests fulfilled by offline fixture; zero live backend requests.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));});
